"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {DEFAULT_ACCOUNTS,createAccount} from "@/lib/accounting/accounts";
import {calculateBalances,calculateStatements,calculateTrialBalance,entryTotals,validateEntryShape} from "@/lib/accounting/engine";
import {parseWorkspace} from "@/lib/accounting/schema";
import type {Account,AccountCategory,EntryKind,JournalEntry,JournalLine,WorkspaceData} from "@/lib/accounting/types";
import {clearWorkspace,loadWorkspace,saveWorkspace} from "@/lib/persistence/workspace-store";

const fmt=(n:number)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(n||0);
const today=()=>new Date().toISOString().slice(0,10);
const uid=(p="id")=>`${p}_${crypto.randomUUID().slice(0,12)}`;
const emptyLine=():JournalLine=>({accountId:"",debit:0,credit:0});
const emptyEntry=(kind:EntryKind="regular"):JournalEntry=>({id:uid("entry"),date:today(),description:"",reference:"",kind,lines:[emptyLine(),emptyLine()]});

type Tab="Dashboard"|"Transactions"|"Accounts"|"Journal"|"Ledger"|"Trial Balance"|"Income Statement"|"Owner's Equity"|"Balance Sheet";

export default function V8Studio(){
 const [w,setW]=useState<WorkspaceData>({version:1,business:"My Business",periodEnd:today(),accounts:DEFAULT_ACCOUNTS,entries:[]});
 const [tab,setTab]=useState<Tab>("Dashboard"); const [entry,setEntry]=useState(emptyEntry); const [notice,setNotice]=useState("");
 const [newAccount,setNewAccount]=useState({code:"",name:"",category:"asset" as AccountCategory}); const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const x=loadWorkspace();if(x)setW(x)},[]); useEffect(()=>{const t=setTimeout(()=>saveWorkspace(w),200);return()=>clearTimeout(t)},[w]);
 const trial=useMemo(()=>calculateTrialBalance(w.accounts,w.entries),[w]); const statements=useMemo(()=>calculateStatements(w.accounts,w.entries),[w]); const balances=useMemo(()=>calculateBalances(w.accounts,w.entries),[w]); const amap=useMemo(()=>new Map(w.accounts.map(a=>[a.id,a])),[w.accounts]);
 const setLine=(i:number,p:Partial<JournalLine>)=>setEntry(e=>({...e,lines:e.lines.map((x,n)=>n===i?{...x,...p}:x)}));
 const post=()=>{const errors=validateEntryShape(entry);if(errors.length){setNotice(errors[0]);return}if(entry.lines.some(l=>!amap.has(l.accountId))){setNotice("Every line must reference an existing account.");return}setW(x=>({...x,entries:[...x.entries,structuredClone(entry)]}));setEntry(emptyEntry(entry.kind));setNotice("Entry posted.");setTab("Journal")};
 const addAccount=()=>{if(!newAccount.code.trim()||!newAccount.name.trim()){setNotice("Account code and name are required.");return}if(w.accounts.some(a=>a.code===newAccount.code.trim())){setNotice("Account code already exists.");return}setW(x=>({...x,accounts:[...x.accounts,createAccount(uid("acct"),newAccount.code.trim(),newAccount.name.trim(),newAccount.category)]}));setNewAccount({code:"",name:"",category:"asset"});setNotice("Account added.")};
 const exportJson=()=>{const b=new Blob([JSON.stringify(w,null,2)],{type:"application/json"});const u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`${w.business.replace(/\W+/g,"-").toLowerCase()||"yoho"}.json`;a.click();URL.revokeObjectURL(u)};
 const importJson=async(f:File)=>{try{const r=parseWorkspace(JSON.parse(await f.text()));if(!r.ok){setNotice(r.errors[0]||"Invalid workspace");return}setW(r.value);setNotice("Workspace imported and validated.")}catch{setNotice("Invalid JSON workspace.")}};
 const reset=()=>{if(confirm("Reset all local accounting data?")){clearWorkspace();setW({version:1,business:"My Business",periodEnd:today(),accounts:DEFAULT_ACCOUNTS,entries:[]});setNotice("Workspace reset.")}};
 const nav:Tab[]=["Dashboard","Transactions","Accounts","Journal","Ledger","Trial Balance","Income Statement","Owner's Equity","Balance Sheet"];
 return <main className="v8-shell"><aside className="v8-side"><div className="v8-brand"><b>Y</b><span><strong>YOHO</strong><small>v8 Accounting Studio</small></span></div><a className="v8-ai" href="/ai">✦ Auto Solver</a><nav>{nav.map(n=><button key={n} className={tab===n?"active":""} onClick={()=>setTab(n)}>{n}</button>)}</nav><div className="v8-side-actions"><button onClick={exportJson}>Export JSON</button><button onClick={()=>fileRef.current?.click()}>Import JSON</button><button onClick={reset}>Reset</button><input ref={fileRef} hidden type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)void importJson(f);e.currentTarget.value=""}}/></div></aside><section className="v8-main"><header className="v8-header"><div><small>ACCOUNTING WORKSPACE</small><input value={w.business} onChange={e=>setW(x=>({...x,business:e.target.value}))}/><label>Period end <input type="date" value={w.periodEnd} onChange={e=>setW(x=>({...x,periodEnd:e.target.value}))}/></label></div><div className={trial.balanced?"v8-ok":"v8-bad"}>{trial.balanced?"✓ Balanced":"! Out of balance"}</div></header>{notice&&<div className="v8-notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}{tab==="Dashboard"&&<Dashboard w={w} trial={trial} s={statements} go={setTab}/>} {tab==="Transactions"&&<Editor entry={entry} accounts={w.accounts} setEntry={setEntry} setLine={setLine} post={post}/>} {tab==="Accounts"&&<Accounts accounts={w.accounts} form={newAccount} setForm={setNewAccount} add={addAccount}/>} {tab==="Journal"&&<Journal entries={w.entries} accounts={amap}/>} {tab==="Ledger"&&<Ledger accounts={w.accounts} balances={balances}/>} {tab==="Trial Balance"&&<Trial trial={trial} accounts={amap}/>} {tab==="Income Statement"&&<Statement title="Income Statement" items={w.accounts.filter(a=>a.category==="revenue"||a.category==="expense").map(a=>[a.name,balances.find(b=>b.accountId===a.id)?.balance||0])} total={["Net Income",statements.netIncome]}/>} {tab==="Owner's Equity"&&<Statement title="Statement of Owner's Equity" items={[["Beginning Capital",statements.contributedCapital],["Net Income",statements.netIncome],["Less: Drawing",-statements.drawings]]} total={["Ending Owner's Equity",statements.endingEquity]}/>} {tab==="Balance Sheet"&&<Statement title="Balance Sheet" items={[["Total Assets",statements.assets],["Total Liabilities",statements.liabilities],["Owner's Equity",statements.endingEquity]]} total={["Liabilities + Equity",statements.liabilities+statements.endingEquity]} footer={statements.balanceSheetBalanced?"Balanced":"Does not balance"}/>}</section></main>
}

function Dashboard({w,trial,s,go}:{w:WorkspaceData;trial:ReturnType<typeof calculateTrialBalance>;s:ReturnType<typeof calculateStatements>;go:(t:Tab)=>void}){return <div className="v8-page"><div className="v8-hero"><div><small>CONTROL CENTER</small><h1>{w.business}</h1><p>Deterministic accounting calculations, validated journal entries, local-first persistence, and a separate AI interpretation layer.</p></div><a href="/ai">Open Auto Solver →</a></div><div className="v8-metrics">{[["Assets",s.assets],["Liabilities",s.liabilities],["Net Income",s.netIncome],["Equity",s.endingEquity]].map(([k,v])=><div key={String(k)}><span>{k}</span><strong>{fmt(Number(v))}</strong></div>)}</div><div className="v8-grid"><section className="v8-card"><h2>Integrity checks</h2><Check name="Trial balance" ok={trial.balanced}/><Check name="Balance sheet" ok={s.balanceSheetBalanced}/><Check name="All journal entries" ok={w.entries.every(e=>validateEntryShape(e).length===0)}/></section><section className="v8-card"><h2>Quick actions</h2><button onClick={()=>go("Transactions")}>+ New transaction</button><button onClick={()=>go("Trial Balance")}>Trial balance</button><button onClick={()=>go("Balance Sheet")}>Balance sheet</button></section></div></div>}
function Check({name,ok}:{name:string;ok:boolean}){return <div className="v8-check"><b>{ok?"✓":"!"}</b><span>{name}<small>{ok?"Passed":"Review required"}</small></span></div>}
function Editor({entry,accounts,setEntry,setLine,post}:{entry:JournalEntry;accounts:Account[];setEntry:React.Dispatch<React.SetStateAction<JournalEntry>>;setLine:(i:number,p:Partial<JournalLine>)=>void;post:()=>void}){const t=entryTotals(entry);return <section className="v8-card"><h2>Transaction Entry</h2><p>Multi-line double-entry posting. The engine rejects unbalanced entries.</p><div className="v8-fields"><input type="date" value={entry.date} onChange={e=>setEntry(x=>({...x,date:e.target.value}))}/><input placeholder="Description" value={entry.description} onChange={e=>setEntry(x=>({...x,description:e.target.value}))}/><input placeholder="Reference" value={entry.reference} onChange={e=>setEntry(x=>({...x,reference:e.target.value}))}/><select value={entry.kind} onChange={e=>setEntry(x=>({...x,kind:e.target.value as EntryKind}))}><option value="regular">Regular</option><option value="adjusting">Adjusting</option><option value="closing">Closing</option></select></div><div className="v8-lines"><div className="v8-line head"><span>Account</span><span>Debit</span><span>Credit</span></div>{entry.lines.map((l,i)=><div className="v8-line" key={i}><select value={l.accountId} onChange={e=>setLine(i,{accountId:e.target.value})}><option value="">Select account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select><input type="number" min="0" step="0.01" value={l.debit||""} onChange={e=>setLine(i,{debit:Number(e.target.value)||0,credit:0})}/><input type="number" min="0" step="0.01" value={l.credit||""} onChange={e=>setLine(i,{credit:Number(e.target.value)||0,debit:0})}/></div>)}</div><div className="v8-actions"><button onClick={()=>setEntry(x=>({...x,lines:[...x.lines,emptyLine()]}))}>+ Add line</button><span className={Math.abs(t.debit-t.credit)<.005?"v8-ok":"v8-bad"}>Dr {fmt(t.debit)} · Cr {fmt(t.credit)}</span><button className="primary" onClick={post}>Post entry</button></div></section>}
function Accounts({accounts,form,setForm,add}:{accounts:Account[];form:{code:string;name:string;category:AccountCategory};setForm:React.Dispatch<React.SetStateAction<{code:string;name:string;category:AccountCategory}>>;add:()=>void}){return <section className="v8-card"><h2>Chart of Accounts</h2><div className="v8-fields"><input placeholder="Code" value={form.code} onChange={e=>setForm(x=>({...x,code:e.target.value}))}/><input placeholder="Account name" value={form.name} onChange={e=>setForm(x=>({...x,name:e.target.value}))}/><select value={form.category} onChange={e=>setForm(x=>({...x,category:e.target.value as AccountCategory}))}>{["asset","contra_asset","liability","equity","contra_equity","revenue","expense"].map(x=><option key={x}>{x}</option>)}</select><button className="primary" onClick={add}>Add account</button></div><div className="v8-table"><table><thead><tr><th>Code</th><th>Account</th><th>Category</th><th>Normal</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td>{a.code}</td><td>{a.name}</td><td>{a.category}</td><td>{a.normalBalance}</td></tr>)}</tbody></table></div></section>}
function Journal({entries,accounts}:{entries:JournalEntry[];accounts:Map<string,Account>}){return <section className="v8-card"><h2>General Journal</h2><div className="v8-table"><table><thead><tr><th>Date</th><th>Description</th><th>Account</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{entries.flatMap(e=>e.lines.map((l,i)=><tr key={`${e.id}-${i}`}><td>{i?"":e.date}</td><td>{i?"":e.description}</td><td>{accounts.get(l.accountId)?.name||"Unknown"}</td><td>{l.debit?fmt(l.debit):""}</td><td>{l.credit?fmt(l.credit):""}</td></tr>))}</tbody></table></div></section>}
function Ledger({accounts,balances}:{accounts:Account[];balances:ReturnType<typeof calculateBalances>}){const m=new Map(balances.map(x=>[x.accountId,x]));return <section className="v8-card"><h2>General Ledger</h2><div className="v8-table"><table><thead><tr><th>Account</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>{accounts.map(a=>{const b=m.get(a.id)!;return <tr key={a.id}><td>{a.code} · {a.name}</td><td>{fmt(b.debit)}</td><td>{fmt(b.credit)}</td><td>{fmt(b.balance)}</td></tr>})}</tbody></table></div></section>}
function Trial({trial,accounts}:{trial:ReturnType<typeof calculateTrialBalance>;accounts:Map<string,Account>}){return <section className="v8-card"><h2>Trial Balance <em className={trial.balanced?"v8-ok":"v8-bad"}>{trial.balanced?"Balanced":"Out of balance"}</em></h2><div className="v8-table"><table><thead><tr><th>Account</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{trial.rows.filter(r=>r.balance).map(r=>{const a=accounts.get(r.accountId)!;return <tr key={r.accountId}><td>{a.code} · {a.name}</td><td>{a.normalBalance==="debit"?fmt(r.balance):""}</td><td>{a.normalBalance==="credit"?fmt(r.balance):""}</td></tr>})}</tbody><tfoot><tr><th>Total</th><th>{fmt(trial.totalDebit)}</th><th>{fmt(trial.totalCredit)}</th></tr></tfoot></table></div></section>}
function Statement({title,items,total,footer}:{title:string;items:[string,number][];total:[string,number];footer?:string}){return <section className="v8-card v8-statement"><h2>{title}</h2>{items.map(([k,v])=><div key={k}><span>{k}</span><b>{fmt(v)}</b></div>)}<div className="total"><span>{total[0]}</span><b>{fmt(total[1])}</b></div>{footer&&<p className={footer==="Balanced"?"v8-ok":"v8-bad"}>{footer}</p>}</section>}
