import Link from "next/link";

export default function Landing(){return <main className="landing-shell">
  <div className="landing-noise"/><div className="landing-orb orb-a"/><div className="landing-orb orb-b"/>
  <nav className="landing-nav glass"><Link href="/" className="brand-mark"><span>Y</span><div><b>YOHO</b><small>Accounting Intelligence</small></div></Link><div className="landing-links"><Link href="/studio">Studio</Link><Link href="/ai">Auto Solver</Link></div><Link className="nav-cta" href="/studio">Open Studio <span>↗</span></Link></nav>
  <section className="landing-hero">
    <div className="hero-copy"><div className="eyebrow"><i/> AI ACCOUNTING WORKSPACE</div><h1>Accounting, <em>without the friction.</em></h1><p>Turn messy accounting problems into structured, validated books. Interpret naturally, calculate deterministically, and move from journal entries to financial statements in one workspace.</p><div className="hero-actions"><Link className="hero-primary" href="/ai">Launch Auto Solver <span>→</span></Link><Link className="hero-secondary" href="/studio">Explore Studio</Link></div><div className="hero-proof"><span>Local AI</span><span>Double-entry validation</span><span>Excel export</span></div></div>
    <div className="landing-preview glass"><div className="preview-glow"/><div className="preview-bar"><span/><span/><span/><b>YOHO / AUTO SOLVER</b></div><div className="preview-status"><div><small>LOCAL ENGINE</small><strong>Qwen 0.5B</strong></div><span className="status-dot"/> Ready</div><div className="preview-ring"><div><small>TRIAL BALANCE</small><strong>₱128,450.00</strong><span>DEBIT = CREDIT</span></div></div><div className="preview-entry"><small>GENERATED JOURNAL</small><div><b>Cash</b><strong>₱50,000.00</strong></div><div><b>Owner's Capital</b><strong>₱50,000.00</strong></div><footer><span>Validation</span><b>✓ Balanced</b></footer></div></div>
  </section>
  <section className="landing-features"><article className="glass"><span className="feature-icon">01</span><div><h3>Interpret</h3><p>Natural-language problems become structured accounting events.</p></div></article><article className="glass"><span className="feature-icon">02</span><div><h3>Calculate</h3><p>Deterministic accounting logic handles the arithmetic and balances.</p></div></article><article className="glass"><span className="feature-icon">03</span><div><h3>Validate</h3><p>Trace entries through ledgers, trial balances and statements.</p></div></article></section>
  <section className="landing-bottom"><span>BUILT FOR STUDENTS, ACCOUNTANTS &amp; BUILDERS</span><Link href="/studio">Enter the workspace →</Link></section>
  <footer className="landing-footer">YOHO · AI-assisted accounting with transparent validation</footer>
</main>}