import Link from "next/link";

export default function Landing(){return <main className="landing-shell">
  <div className="landing-noise"/><div className="landing-orb orb-a"/><div className="landing-orb orb-b"/>
  <nav className="landing-nav glass"><Link href="/" className="brand-mark"><span>Y</span><div><b>YOHO</b><small>Accounting Intelligence</small></div></Link><div className="landing-links"><Link href="/studio">Studio</Link><Link href="/ai">Auto Solver</Link></div><Link className="nav-cta" href="/studio">Open Studio <span>↗</span></Link></nav>
  <section className="landing-hero">
    <div className="hero-copy"><div className="eyebrow"><i/> AI ACCOUNTING WORKSPACE</div><h1>Accounting, <em>without the friction.</em></h1><p>Turn messy accounting problems into structured, validated books. Interpret naturally, calculate deterministically, and move from journal entries to financial statements in one workspace.</p><div className="hero-actions"><Link className="hero-primary" href="/ai">Launch Auto Solver <span>→</span></Link><Link className="hero-secondary" href="/studio">Explore Studio</Link></div><div className="hero-proof"><span>Local AI</span><span>Double-entry validation</span><span>Excel export</span></div></div>
    <div className="landing-preview glass"><div className="preview-glow"/><div className="preview-bar"><span/><span/><span/><b>YOHO / AUTO SOLVER</b></div><div className="preview-status"><div><small>LOCAL ENGINE</small><strong>Qwen 0.5B</strong></div><span className="status-dot"/> Ready</div><div className="preview-ring"><div><small>TRIAL BALANCE</small><strong>₱128,450.00</strong><span>DEBIT = CREDIT</span></div></div><div className="preview-entry"><small>GENERATED JOURNAL</small><div><b>Cash</b><strong>₱50,000.00</strong></div><div><b>Owner's Capital</b><strong>₱50,000.00</strong></div><footer><span>Validation</span><b>✓ Balanced</b></footer></div></div>
  </section>
  <section className="landing-bento">
    <article className="bento-card bento-ai glass"><div className="bento-label">01 · AUTO SOLVER</div><h2>From messy words<br/><span>to balanced books.</span></h2><p>Upload or paste an accounting problem. Yoho structures the transaction, applies accounting logic, and validates the result.</p><div className="bento-mini"><div className="mini-line"><span>Cash</span><b>₱50,000</b></div><div className="mini-line"><span>Owner's Capital</span><b>₱50,000</b></div><div className="mini-status">✓ DEBIT = CREDIT</div></div><Link href="/ai">Try Auto Solver <span>↗</span></Link></article>
    <article className="bento-card bento-engine glass"><div className="bento-label">02 · ACCOUNTING ENGINE</div><div className="engine-visual"><div className="engine-node">DR</div><div className="engine-line"/><div className="engine-node bright">CR</div></div><h3>Double-entry<br/>at the core.</h3><p>Every transaction remains traceable and balanced.</p></article>
    <article className="bento-card bento-statements glass"><div className="bento-label">03 · STATEMENTS</div><div className="statement-head"><span>NET INCOME</span><b>₱168,000</b></div><div className="bars"><i/><i/><i/><i/><i/><i/></div><div className="statement-meta"><span>Revenue</span><b>₱250,000</b><span>Expenses</span><b>₱82,000</b></div><h3>See the whole picture.</h3></article>
    <article className="bento-card bento-local glass"><div className="bento-label">04 · LOCAL AI</div><div className="local-orb"><span/></div><div><h3>Private by design.</h3><p>Inference runs locally when supported. No accounting data needs to leave your browser.</p></div><div className="local-tags"><span>WebGPU</span><span>Local</span><span>Offline-ready</span></div></article>
    <article className="bento-card bento-flow glass"><div className="bento-label">ACCOUNTING FLOW</div><div className="flow"><span>Problem</span><i>→</i><span>Journal</span><i>→</i><span>Ledger</span><i>→</i><span>Statements</span></div><p>One workspace. One source of truth.</p></article>
  </section>
  <section className="landing-bottom"><span>BUILT FOR STUDENTS, ACCOUNTANTS &amp; BUILDERS</span><Link href="/studio">Enter the workspace →</Link></section>
  <footer className="landing-footer">YOHO · AI-assisted accounting with transparent validation</footer>
</main>}